server:
  port: 8080

spring:
  datasource:
    name: ${MYSQL_HOST}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    url: jdbc:mysql://${MYSQL_HOST}:3306/${DATABASE_NAME}?characterEncoding=UTF8&userSSL=false
  jpa:
    generate-ddl: false
  flyway:
    enabled: true
  config:
    import: optional:file:.env[.properties]